//
// Created by MartinF on 07/03/2022.
//

#ifndef MFRANCESCHI_CPPLIBRARIES_LIGHTWINDOWS_HPP
#define MFRANCESCHI_CPPLIBRARIES_LIGHTWINDOWS_HPP

#if MF_WINDOWS
#    define WIN32_LEAN_AND_MEAN 1

#    include <Windows.h>
#endif

#endif // MFRANCESCHI_CPPLIBRARIES_LIGHTWINDOWS_HPP
