//
// Created by MartinF on 23/04/2022.
//

#ifndef MFRANCESCHI_CPPLIBRARIES_SHARED_LIBS_TESTS_COMMON_HPP
#define MFRANCESCHI_CPPLIBRARIES_SHARED_LIBS_TESTS_COMMON_HPP

#include "MF/SharedLibs.hpp"

using namespace ::MF::SharedLibs;

#endif // MFRANCESCHI_CPPLIBRARIES_SHARED_LIBS_TESTS_COMMON_HPP
